Task #2
ozoncp/ocp-suggestion-api pull request #2
Opened 2021-07-18 15:32 UTC by alexander-yakovlev

2021-07-18 20:40 UTC, Maklayna requested changes

2021-07-18 20:40 UTC, Maklayna commented on internal/utils/convert_map.go
> +	var out_map = make(map[string]string, len(in_map))
Здесь и далее, лучше заменить var на := если сразу идет инициализация переменной

2021-07-18 20:40 UTC, Maklayna commented on internal/utils/convert_map.go
> +	var out_map = make(map[string]string, len(in_map))
Без проверки на nil, при входной nil мапе вернем замейканую путую мапу.

2021-07-18 20:40 UTC, Maklayna commented on internal/utils/filter_slice.go
> +	var in_filter = map[int]struct{}{ //Захардкоженный фильтр
Стоит вынести за пределы функции, иначе при каждом вызове произойдет пересоздание хардкодных данных

2021-07-18 20:40 UTC, Maklayna commented on internal/utils/filter_slice.go
> +	out_slice := make([]int, 0)
Так заранее сколько значений попадет по фильтру неизвестно, стоит аллоцировать слайс любой стартовой емкости, зависящей от длинны входного массива, но не 0. Так снизится число аллокаций при расширении слайса.

2021-07-18 20:40 UTC, Maklayna commented on internal/utils/slice_to_chunk.go
> +	if chunk_size <= 0 {
На мой взгляд реализация выбрана не очень удачно, и есть более элегантные решения, без жонглирования -1 +1 что сильно снижает читаемость.

2021-07-18 20:40 UTC, Maklayna commented on internal/utils/filter_slice.go
> +	var in_filter = map[int]struct{}{ //Захардкоженный фильтр
Проверка на nil для консистентности возврата, так же бы не помешала.

2021-07-18 20:40 UTC, Maklayna commented on internal/utils/filter_slice.go
> +		5: {}}
Скобку бы на отдельную строку

2021-07-18 20:40 UTC, Maklayna commented on internal/utils/convert_map.go
> +func ConvertMap(in_map map[string]string) (map[string]string, error) {
Спасибо за задание в комменте, удобненько.  Но на всякий случай уточню, что принято коменты к экспортируем методам делать //METHOD_NAME .........

2021-07-19 15:48 UTC, alexander-yakovlev commented on internal/utils/convert_map.go
> +func ConvertMap(in_map map[string]string) (map[string]string, error) {
Ок! Сделал

2021-07-19 15:49 UTC, alexander-yakovlev commented on internal/utils/filter_slice.go
> +	var in_filter = map[int]struct{}{ //Захардкоженный фильтр
Добавил везде проверки на nil, с возвращением ошибки.

2021-07-19 15:49 UTC, alexander-yakovlev commented on internal/utils/slice_to_chunk.go
> +	if chunk_size <= 0 {
Поменял реализацию

2021-07-19 15:52 UTC, alexander-yakovlev reviewed
Спасибо за подробные замечания, исправил!

2021-07-20 16:02 UTC, Maklayna commented on internal/utils/slice_to_chunk.go
> +	out_slice := make([][]int, 0)
Вот тут, нам длинна нового слайса точно известна, и можно было бы сразу на нее взять емкость.

2021-07-20 16:03 UTC, Maklayna approved these changes

2021-07-20 18:43 UTC, alexander-yakovlev commented on internal/utils/slice_to_chunk.go
> +	out_slice := make([][]int, 0)
Да, я думал, какую бы емкость тут сразу задать, ничего не придумал, поэтому оставил 0 )
Тут же двумерный слайс, и вызов make([][]int, 0, len(in_slice)) выделит емкость под первое измерение (количество "внутренних" слайсов). И оно, скорее всего, будет не тем, чем нужно.
Или это нормальный вариант? 
Или тут вернуть первоначальный расчёт для количества чанков:
`num_chunks := (len(in_slice)-1)/chunk_size + 1`
Затем выделить под первое измерение:
`out_slice := make([][]int, 0, num_chunks)`
И в цикле под второе?:
```
for i := range out_slice {
    out_slice[i] = make([]int, 0, chunk_size)
}
```
Как оптимальнее для слайса слайсов?

2021-07-20 18:45 UTC, merged

2021-07-20 20:08 UTC, Maklayna commented on internal/utils/slice_to_chunk.go
> +	out_slice := make([][]int, 0)
Вполне достаточно задать размер самого слайса. Внутренние слайсы ты все равно никак не оптимизирушь в плане выделения памяти, потому как их размер заранее определен когда ты берешь подслайс от исходного. А вообще, если интересно, можно погонять бенчмарки(у го есть встроенные возможности для этого) с предварительной аллокацией и без и посмотреть на результат.