Task #3
ozoncp/ocp-suggestion-api pull request #3
Opened 2021-07-24 18:14 UTC by alexander-yakovlev

1. Реализация открытия и закрытия файла в цикле, используя defer и функтор в cmd/…/main.go
2. Описание структуры для своей предметной области и реализация методов работы с ней в internal/models/…go
3. Реализация в пакете internal/utils для своей структуры функций: 
    - батчевого разделения слайса на слайс слайсов;
    - конвертации слайса от структуры в отображение.

2021-07-24 18:26 UTC, alexander-yakovlev commented on internal/utils/slice_to_chunk_test.go
> +
Написал бенчмарки, чтобы проверить производительность с предварительной аллокацией и без и вот результат (go test -bench=. -benchtime=10000x -count=5):
```
goos: linux
goarch: amd64
pkg: github.com/ozoncp/ocp-suggestion-api/internal/utils
cpu: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
BenchmarkSliceToChunk-4       	   10000	       143.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkSliceToChunk-4       	   10000	       144.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkSliceToChunk-4       	   10000	       135.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkSliceToChunk-4       	   10000	       150.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkSliceToChunk-4       	   10000	       139.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkSliceToChunkMake-4   	   10000	      1035 ns/op	      24 B/op	       1 allocs/op
BenchmarkSliceToChunkMake-4   	   10000	       829.9 ns/op	      24 B/op	       1 allocs/op
BenchmarkSliceToChunkMake-4   	   10000	      1108 ns/op	      24 B/op	       1 allocs/op
BenchmarkSliceToChunkMake-4   	   10000	       661.7 ns/op	      24 B/op	       1 allocs/op
BenchmarkSliceToChunkMake-4   	   10000	      1134 ns/op	      24 B/op	       1 allocs/op
PASS
ok  	github.com/ozoncp/ocp-suggestion-api/internal/utils	8.094s
```

Пока вывод такой (если в тестах нет ошибок), что в данном случае лучше не создавать слайс при помощи make. Тогда слайс просто мапируется на слайс слайсов без перевыделения памяти, что работает в 4-7 раз быстрее, чем с предаллокацией make.

2021-07-26 20:27 UTC, Maklayna requested changes

2021-07-26 20:27 UTC, Maklayna commented on Makefile
> +run:	build
а почему не go run?

2021-07-26 20:27 UTC, Maklayna commented on Makefile
> +	go mod tidy
если мне память не изменяет build под капотом сам сделает tidy

2021-07-26 20:27 UTC, Maklayna commented on cmd/ocp-suggestion-api/main.go
> +			}
На мой вкус именованный возврат в таком виде плохая практика, читаемость заметно снижается, это в принципе видно по необходимости оставлять коменты.

2021-07-26 20:27 UTC, Maklayna commented on cmd/ocp-suggestion-api/main.go
> +			closeErr := file.Close()
А если была ошибка открытия файла и  file == nil?

2021-07-26 20:27 UTC, Maklayna commented on internal/models/suggestion.go
> +	Id       uint64
ID вместо Id скажет тебе линтер

2021-07-26 20:27 UTC, Maklayna commented on internal/models/suggestion.go
> +	UserId   uint64
UserID

2021-07-26 20:27 UTC, Maklayna commented on internal/models/suggestion.go
> +	CourseId uint64
тоже самое

2021-07-26 20:27 UTC, Maklayna commented on internal/models/suggestion.go
> +}
Если структура не имеет инит метода, да и сама публичная, в конструкторе нет необходимости

2021-07-26 20:27 UTC, Maklayna commented on internal/models/suggestion.go
> +func NewSuggestion(id, userid, courseid uint64) Suggestion {
camelCase

2021-07-26 20:27 UTC, Maklayna commented on internal/models/suggestion.go
> +		"Suggestion{Id: %v, UserId: %v, CourseId: %v}",
лучше более корректные глаголы типа %d

2021-07-26 20:27 UTC, Maklayna commented on internal/utils/suggestion_map.go
> +				ErrDuplicateKey, outMap[elem.Id], elem)
обычно оборачиваемая ошибка передается в конце.

2021-07-26 20:27 UTC, Maklayna commented on internal/utils/suggestion_split.go
> +
а зачем приведение к uint?

2021-07-26 20:27 UTC, Maklayna commented on internal/utils/slice_to_chunk_test.go
> +
Удивительно. Но бенчмарк не врет, если запутить  `go build -gcflags '-m -m' ./internal/utils/slice_to_chunk.go`, видно что он потащит замейканый слайс в кучу. А вот почему первый вариант остается на стеке я сказать не могу...

2021-07-26 21:10 UTC, Maklayna commented on internal/utils/slice_to_chunk_test.go
> +
Ну и в дополнение если написать бенч так (пушнуть прав нет)
`package utils

import (
	"testing"
)

var s1 = make([]int, 4500)
var s2 = make([]int, 50000)
var s3 = make([]int, 150000)

func DoBenchmarks(f func(in_slice []int, chunk_size int) ([][]int, error)) {
	f(s1, 20)
	f(s2, 20)
	f(s3, 20)
	f(s1, 200)
	f(s2, 200)
	f(s3, 200)
	f(s1, 1000)
	f(s2, 1000)
	f(s3, 1000)
}

func BenchmarkSliceToChunk(b *testing.B) {
	for i := 0; i < b.N; i++ {
		DoBenchmarks(SliceToChunk)
	}
	b.ReportAllocs()
}

func BenchmarkSliceToChunkMake(b *testing.B) {
	for i := 0; i < b.N; i++ {
		DoBenchmarks(SliceToChunkMake)
	}
	b.ReportAllocs()
}` 
результат будет более ожидаемый 
`goos: darwin
goarch: amd64
pkg: github.com/ozoncp/ocp-suggestion-api/internal/utils
BenchmarkSliceToChunk-8            10000            305348 ns/op         1172218 B/op         89 allocs/op
BenchmarkSliceToChunk-8            10000            319749 ns/op         1172219 B/op         89 allocs/op
BenchmarkSliceToChunk-8            10000            308707 ns/op         1172218 B/op         89 allocs/op
BenchmarkSliceToChunk-8            10000            328245 ns/op         1172219 B/op         89 allocs/op
BenchmarkSliceToChunk-8            10000            331953 ns/op         1172219 B/op         89 allocs/op
BenchmarkSliceToChunkMake-8        10000             89325 ns/op          282562 B/op          9 allocs/op
BenchmarkSliceToChunkMake-8        10000             91856 ns/op          282562 B/op          9 allocs/op
BenchmarkSliceToChunkMake-8        10000             91659 ns/op          282562 B/op          9 allocs/op
BenchmarkSliceToChunkMake-8        10000             91166 ns/op          282562 B/op          9 allocs/op
BenchmarkSliceToChunkMake-8        10000             90600 ns/op          282563 B/op          9 allocs/op
`

2021-07-26 21:44 UTC, Maklayna commented on internal/utils/slice_to_chunk_test.go
> +
В общем не стоит читать код по ночам после завала :Р
```
	data := make([]int, 0, size_data)
	b.ResetTimer() // remove time of allocation
	for i := 0; i < b.N; i++ {
		for j := range data { // prepare data
			data[j] = i ^ j ^ 0x2cc
		}
```
Вот это вот  ^  всегда передает пустой слайс в бенчмарк (так как range перебирает по длине, а не по емкости), вот и выходит что в первом случае для разбития слайса 0 длинны надо 0 алокаций, а во втором мы принудительно делаем одну аллокацию. Если передавать слайс не 0 длинны, все будет честно и вполне ожидаемо =)

2021-07-27 03:27 UTC, alexander-yakovlev commented on internal/utils/slice_to_chunk_test.go
> +
Да, точно, создавался slice нулевой длины, вот и инициализации не было. Ошибка в тесте.
Взял предлагаемый вариант теста, с передачей функции больше понравился.

2021-07-27 03:27 UTC, alexander-yakovlev commented on Makefile
> +run:	build
Привычка от C++ ) 
А тут точно, можно же go run.

2021-07-27 03:27 UTC, alexander-yakovlev commented on Makefile
> +	go mod tidy
Да, делает, но почему-то go.sum получается меньше, чем при go mod tidy (одну строку не включает).
Вот из этих двух добавляет только вторую:
```
gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 h1:yhCVgyC4o1eVCa2tZl7eS0r+SDo693bJlVdllGtEeKM=
gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405/go.mod h1:Co6ibVJAznAaIkqp8huTwlJQCZ016jof/cbN4VW5Yz0=
```
Оставил пока go mod tidy

2021-07-27 03:27 UTC, alexander-yakovlev commented on cmd/ocp-suggestion-api/main.go
> +			}
Переписал возврат.

2021-07-27 03:28 UTC, alexander-yakovlev commented on cmd/ocp-suggestion-api/main.go
> +			closeErr := file.Close()
По идее сюда не должен добраться, так как в случае err != nil return. Но добавил ещё проверку на file == nil

2021-07-27 03:28 UTC, alexander-yakovlev commented on internal/models/suggestion.go
> +	Id       uint64
Тут и ниже исправил на ID

2021-07-27 03:28 UTC, alexander-yakovlev commented on internal/models/suggestion.go
> +}
Ок, убрал конструктор.

2021-07-27 03:28 UTC, alexander-yakovlev commented on internal/models/suggestion.go
> +		"Suggestion{Id: %v, UserId: %v, CourseId: %v}",
Ок

2021-07-27 03:28 UTC, alexander-yakovlev commented on internal/utils/suggestion_map.go
> +				ErrDuplicateKey, outMap[elem.Id], elem)
Ок

2021-07-27 03:28 UTC, alexander-yakovlev commented on internal/utils/suggestion_split.go
> +
uint/int mistmatch: batchSize - uint, а len возвращает int. Вот и добавил приведение, чтобы не было ошибки.

2021-07-27 05:33 UTC, Maklayna commented on cmd/ocp-suggestion-api/main.go
> +			closeErr := file.Close()
Ну тогда и смысла нет проверять на ошибку == nil, если с ошибкой мы не дойдем до дефера.

2021-07-27 05:43 UTC, Maklayna commented on cmd/ocp-suggestion-api/main.go
> +		}
Вобщем не это я имел ввиду, меня ввела в заблуждение, проверка на ошибку чтения файла в дефере, а при наличии такой ошибки  file == nil. И либо проверка не нужна была, либо нужна была доп проверка на  nil  перед file.close() если в дефере предполагается обработка ошибки открытия. Сейчас вышло странно.

2021-07-27 05:44 UTC, Maklayna approved these changes

2021-08-01 04:33 UTC, alexander-yakovlev commented on cmd/ocp-suggestion-api/main.go
> +			closeErr := file.Close()
Ок, уберу в следующей итерации

2021-08-01 04:33 UTC, merged