Task #5
ozoncp/ocp-suggestion-api pull request #5
Opened 2021-08-07 12:02 UTC by alexander-yakovlev

Добавлен интерфейс Saver.
Имплементация saver с периодическим сохранением.
Тестовые сценарии для saver с помощью ginkgo и gomega.

2021-08-08 20:09 UTC, Maklayna requested changes
Из основного: 

1. Тесты должны проверять реальные сценарии приложения, условно если проверяем флаш, в кеше должно стать пусто, пока тесты абсолютно непоказательные.
2.  Не стоит нарушать принцип закрытия каналов, есть много статей на этот счет и все они сводятся к тому, что если ваш кейс заставляет вас нарушить это правило, значит вам стоит подумать еще.
3.  Ну и паник стоит избегать.

2021-08-08 20:09 UTC, Maklayna commented on internal/saver/saver.go
> +func NewSaver(ctx context.Context, capacity uint, flusher flusher.Flusher, period time.Duration) Saver {
Лучше придерживаться подхода принимай интерфейсы возвращай структуры. От возврата интерфейса практической пользы нет, да и любая структуры может удовлетворять нескольким интерфейсам,

2021-08-08 20:09 UTC, Maklayna commented on internal/saver/saver.go
> +		return ErrNilPointer
Есть ощущение что сюда мы не попадем при стандартном воркфлоу, ибо  получим панику раньше

2021-08-08 20:09 UTC, Maklayna commented on internal/saver/saver.go
> +		return ErrCapacityOverflow
Прям какое-то очень спорное решение терять данные, вместо увеличения объема слайса. Если уж по какой-то причине мы не хотим выходить за капасити, то нужен какой-то фолбек, просто так выкидывать данные не вариант.

2021-08-08 20:09 UTC, Maklayna commented on internal/saver/saver.go
> +func (s *saver) run(ctx context.Context) {
Мб проглядел, но как мы будем его запускать если run приватный?

2021-08-08 20:09 UTC, Maklayna commented on internal/saver/saver.go
> +			if leftNum, err := s.flush(ctx); err != nil {
Флашить в контексте старта приложения не стоит, лучше завести свой, причем желательно с таймаутом, вдруг флаш зависнет

2021-08-08 20:09 UTC, Maklayna commented on internal/saver/saver.go
> +			close(s.closeCh)
небезопасно закрывать канал из ресивера.

2021-08-08 20:09 UTC, Maklayna commented on internal/saver/saver_test.go
> +		It("should panic when Close", func() {
очень странный тест, лучше сделать чтобы приложение не бросало паник чем проверять что они будут :)

2021-08-08 20:09 UTC, Maklayna commented on internal/saver/saver_test.go
> +			mockFlusher.EXPECT().
по-моему этот тест не проверяет то что указано у него в названии, а просто дубликат предыдущего

2021-08-08 20:09 UTC, Maklayna commented on internal/saver/saver_test.go
> +		It("should not save to flusher", func() {
опять таки нет проверки что что-то зафлашилось, только добавилось в кэш

2021-08-10 20:24 UTC, alexander-yakovlev commented on internal/saver/saver.go
> +func NewSaver(ctx context.Context, capacity uint, flusher flusher.Flusher, period time.Duration) Saver {
В итоге сделал возврат структуры, чтобы воспользоваться доступом к приватным полям в тесте.

2021-08-10 20:24 UTC, alexander-yakovlev commented on internal/saver/saver.go
> +		return ErrNilPointer
Да, убрал. И во flusher тоже.

2021-08-10 20:29 UTC, alexander-yakovlev commented on internal/saver/saver.go
> +		return ErrCapacityOverflow
Начальная задумка была, что Saver нужен для буферизации и только периодического сохранения (чтобы, например, не нагружать репозиторий), поэтому и была ошибка. Сейчас сделал, что при привышении capacity делается flush данных. Могут быть и другие варианты: увеличение capacity, выкидывание самых старых данных (хотя это тоже будет не вариант).

2021-08-10 20:30 UTC, alexander-yakovlev commented on internal/saver/saver.go
> +			if leftNum, err := s.flush(ctx); err != nil {
Добавил таймаут в flush

2021-08-10 20:31 UTC, alexander-yakovlev commented on internal/saver/saver.go
> +			close(s.closeCh)
Да, поэтому в тесте была проверка на панику :) 
Сейчас сделал защищённый мьютексом вариант.

2021-08-10 20:31 UTC, alexander-yakovlev commented on internal/saver/saver_test.go
> +		It("should panic when Close", func() {
Ок, убрал панику.

2021-08-10 20:33 UTC, alexander-yakovlev commented on internal/saver/saver_test.go
> +			mockFlusher.EXPECT().
Тесты поменял и дополнил

2021-08-13 05:35 UTC, Maklayna approved these changes

2021-08-13 16:49 UTC, merged