Task #7
ozoncp/ocp-suggestion-api pull request #7
Opened 2021-08-22 14:40 UTC by alexander-yakovlev

Реализация методов для интерфейса Repo (работа с БД) + логгирование + тесты.
Ручки переведены на работу с repo + логгирование + тесты.

2021-08-23 09:06 UTC, Maklayna requested changes

2021-08-23 09:06 UTC, Maklayna commented on cmd/ocp-suggestion-api/main.go
> +	_ "github.com/lib/pq"
почему не pgx?

2021-08-23 09:06 UTC, Maklayna commented on cmd/ocp-suggestion-api/main.go
> +}
Зачем делать экспортируемые поля неэспортируемой структуры?

2021-08-23 09:06 UTC, Maklayna commented on cmd/ocp-suggestion-api/main.go
> +func connectDB(cfg *config) (*sqlx.DB, error) {
холиварно, но мне ближе наличие  Init метода у репозитория.

2021-08-23 09:06 UTC, Maklayna commented on cmd/ocp-suggestion-api/main.go
> +}
Нашел парс в них env, вопрос снят.

2021-08-23 09:06 UTC, Maklayna commented on internal/repo/repo.go
> +	if sqlStr, args, err := query.ToSql(); err != nil {
кмк бессмысленная проверка. Метод нужен когда запросы идут не из сквирела.

2021-08-23 09:06 UTC, Maklayna commented on internal/repo/repo.go
> +
не хватает проверки rows.Err() в pgx например там могут оказаться внутренние ошибки базы которых больше нигде нет. Например по моему туда идут relation not exist и всякие синтаксические ошибки. Драйверо зависимая фишка, но проверять стоит всегда.

2021-08-23 09:06 UTC, Maklayna commented on internal/db/db.go
> +package db
не ясен смысл пакета.

2021-08-23 09:06 UTC, Maklayna commented on internal/repo/repo.go
> +
не хватает defer rows.Close(), течь будет

2021-08-23 09:06 UTC, Maklayna commented on internal/repo/repo.go
> +		Suffix("RETURNING \"id\"").
с возвращаемыми строками чаще всего очень геморойно обрабатывать ошибки. Так как приходится использовать не Exec

2021-08-23 15:34 UTC, alexander-yakovlev commented on cmd/ocp-suggestion-api/main.go
> +	_ "github.com/lib/pq"
Что-то сразу не разобрался, что для совместимости со стандартным database/sql нужно использовать 
github.com/jackc/pgx/v4/stdlib
Заменил.

2021-08-23 15:34 UTC, alexander-yakovlev commented on cmd/ocp-suggestion-api/main.go
> +func connectDB(cfg *config) (*sqlx.DB, error) {
Раз холиварно, не буду ничего менять )

2021-08-23 15:34 UTC, alexander-yakovlev commented on internal/repo/repo.go
> +	if sqlStr, args, err := query.ToSql(); err != nil {
ToSql() тут нужен исключительно мне для интереса, какой запрос в результате выдаёт squirrel.
А ошибка возвращается ToSql(), значит её нужно проверить )

2021-08-23 15:35 UTC, alexander-yakovlev commented on internal/repo/repo.go
> +
Спасибо, да, rows.Err() рекомендуют использовать после итерирования, добавил.

2021-08-23 15:35 UTC, alexander-yakovlev commented on internal/db/db.go
> +package db
Да, пакет db не нужен. Это я экспериментировал с Interceptor и пробросом подключения к БД в контекст. А потом пакет не убрал.

2021-08-23 15:35 UTC, alexander-yakovlev commented on internal/repo/repo.go
> +
Добавил.

2021-08-23 15:35 UTC, alexander-yakovlev commented on internal/repo/repo.go
> +		Suffix("RETURNING \"id\"").
Хотел использовать Exec + LastInsertId(), но Postgres не поддерживает такую конструкцию, и предлагают использовать RETURNING id для данного варианта.

2021-08-24 21:21 UTC, Maklayna approved these changes

2021-08-25 03:09 UTC, merged